#!/bin/bash

# Script de diagnostic complet pour voir si les emails partent

echo "=========================================="
echo "DIAGNOSTIC COMPLET EMAIL PRODUCTION"
echo "=========================================="
echo ""

echo "📋 VÉRIFICATIONS À FAIRE SUR RENDER SHELL:"
echo ""
echo "1. Vérifier que Supervisor tourne:"
echo "   ps aux | grep supervisor"
echo ""
echo "2. Vérifier que le queue worker tourne:"
echo "   ps aux | grep 'queue:work'"
echo ""
echo "3. Voir les logs du queue worker:"
echo "   tail -100 /var/log/queue-worker.log"
echo ""
echo "4. Voir les derniers logs Laravel (emails):"
echo "   tail -200 storage/logs/laravel.log | grep -i 'email\\|mail\\|CompteCreated\\|SendClientNotification'"
echo ""
echo "5. Compter les jobs en attente:"
echo "   php artisan queue:monitor"
echo ""
echo "6. Voir les failed jobs:"
echo "   php artisan queue:failed"
echo ""
echo "7. Tester l'envoi SMTP direct:"
echo "   php test_smtp_direct.php"
echo ""
echo "=========================================="
echo "ANALYSE DU PROBLÈME"
echo "=========================================="
echo ""
echo "Votre configuration actuelle:"
echo "  ✅ Supervisor configuré (supervisord.conf)"
echo "  ✅ Queue worker défini (laravel-queue-worker)"
echo "  ✅ Event CompteCreated dispatché (CompteService.php:556)"
echo "  ✅ EventServiceProvider enregistré"
echo ""
echo "❌ MAIS: SendClientNotification n'implémente PAS ShouldQueue"
echo "   → Les emails sont envoyés DIRECTEMENT (synchrone)"
echo "   → Le queue worker NE SERT À RIEN actuellement"
echo ""
echo "Solutions possibles:"
echo ""
echo "A) Si SMTP fonctionne (test réussi):"
echo "   → L'email devrait partir immédiatement"
echo "   → Vérifier storage/logs/laravel.log"
echo "   → Chercher 'Email envoyé' ou erreur SMTP"
echo ""
echo "B) Si SMTP ne fonctionne pas:"
echo "   → Vérifier les credentials Gmail dans .env Render"
echo "   → Tester: php test_smtp_direct.php"
echo ""
echo "C) Si rien ne se passe:"
echo "   → Le Listener n'est peut-être pas appelé"
echo "   → Vérifier EventServiceProvider"
echo "   → Vérifier php artisan event:list"
echo ""
echo "=========================================="
echo "COMMANDES DE DEBUG RENDER"
echo "=========================================="
echo ""
echo "# Voir les 50 dernières lignes de logs Laravel"
echo "tail -50 storage/logs/laravel.log"
echo ""
echo "# Chercher les logs d'email"
echo "grep -i 'email\\|mail\\|smtp' storage/logs/laravel.log | tail -20"
echo ""
echo "# Chercher les events dispatchés"
echo "grep -i 'CompteCreated\\|Dispatch event' storage/logs/laravel.log | tail -10"
echo ""
echo "# Chercher les erreurs"
echo "grep -i 'error\\|exception\\|failed' storage/logs/laravel.log | tail -20"
echo ""
echo "=========================================="
